### ISSUE TITLE
control rod slider buttons and server spam reduction.

### ISSUE THREAD

**Issue by Work-work** [sidoh/reactor_simulator_ui#3]
Hi, I wasn't sure where to leave comments :)

A suggestion: +/-  1% and 10% buttons  to the fuel rod % slider. With a sight delay built in so it doesn't submit a request to recalculate each time an adjustment is made. it's annoying to try to adjust / optimize by moving such a small bar 1% at a time.

Idea: Optimization button for RF/tick by adjusting fuel rod %. 

Also a similar delay on recalculating when adding blocks to the reactor, maybe a 2 second delay from last block placed ? If I am building it, I am adding a lot of blocks and don't need to update for each block.

Idea:  a button to turn recalculating on/off while building would be easier than coding a delay.

**Comment by sidoh** [comment]
Great ideas.

**Comment by sidoh** [comment]
Added a toggle for auto-updates. Might have to refresh to see it.

**Comment by sidoh** [comment]
Also added:
- buttons to add/subtract 1%, 5%, and 10% from the control rod insertion slider.
- an "optimize" button for control rod insertion that chooses the optimal value.

I think adding a delay between auto-update requests is obviated by the auto-update toggle. I'll close this for now, but feel free to re-open.

**Comment by Work-work** [comment]
Excellent work Sir! It feels so much smoother to do the edits with auto-update off!
